### ISSUE TITLE
Sonderzeichen &#;

### ISSUE THREAD

**Issue by ziegelwiese** [cracker0dks/Familienduell#2]
Hallo,

Vielen Dank für die Umsetzung! Das wist wirklich das beste Familienduell, was ich bisher gesehen habe.

Ich bastele gerade an Fragen für die polnische Familie und habe Probleme mit Sonderzeichen.
Im base64 gebe ich zum Beispiel &#379; oder &#281; ein*. In der Antwort-Vorschau und oben in der Fragezeile werden die auch wie gewünscht dargestellt.
Aber wenn ich die Anzeigen will schreibt er die Zeichenkette als Plaintext, also er schreibt &#279; wirklich aus.
Ich nehme an, das liegt daran, dass ja die Zeichen der Antworten nach einander einzeln ausgelesen werden. Man müsste also beim Auslesen eine kleine Wenn-Schleife einbauen, die auf & und # reagiert und dann die Zeichenfolge &#222; als ein Zeichen weitergibt.

Leider bin ich des Codierens nicht fähig und kann mir hier nicht selber helfen.

Grüße

*Kodieren in 8859-2 funktioniert nicht

**Comment by cracker0dks** [comment]
Stimmt und gefixed. Nun sollten auch alle Spezialzeichen unterstützt werden. https://github.com/cracker0dks/Familienduell/commit/4f0768282f8aad00b36bd3f55db8c4c386d70c99
