### ISSUE TITLE
Anzeige von längeren Fragen

### ISSUE THREAD

**Issue by michaelsandner** [cracker0dks/Familienduell#9]
Gibts die Möglichkeit auch längere Fragen über mehrere Zeilen anzeigen zu lassen, ohne dass die Frage mit "..." getrimmt wird?

**Comment by cracker0dks** [comment]
Ja, gibt es. Du musst allerdings eine Datei bearbeiten. Geh mal in die Datei server/web/css/main.css ganz nach unten. 
Wenn du dort bei `#displayQuestions` das `white-space: nowrap;` entfernst, wird die Frage nicht mehr abgeschnitte. Das Problem ist jedoch, dass du dann die Antworten mit deiner Frage überdeckst. Als Lösung könntest du: `font-size: 1em;` dort einfügen um die Schrift zu verkleinern.

**Comment by michaelsandner** [comment]
hab als Alternative auch mal das padding der Antworten vergrößter wenn ich nie denn Fall hab, dass ich 6 Antworten hab
